"""Add columns to service_sales and product_sales

Revision ID: 9474070167eb
Revises: 0fefd995a009
Create Date: 2025-08-05 10:47:29.366340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9474070167eb'
down_revision: Union[str, Sequence[str], None] = '0fefd995a009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_sales', 'category')
    op.drop_column('product_sales', 'subcategory')
    op.drop_column('product_sales', 'product')
    op.add_column('service_sales', sa.Column('refund', sa.Float(), nullable=True))
    op.drop_column('service_sales', 'subcategory')
    op.drop_column('service_sales', 'service')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_sales', sa.Column('service', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('service_sales', sa.Column('subcategory', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('service_sales', 'refund')
    op.add_column('product_sales', sa.Column('product', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('product_sales', sa.Column('subcategory', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('product_sales', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
